---
title: "Weakest link models for pairs, applied to PAM50 genes"
output: 
  html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
require(WeakestLink)
require(survival)
library(GenSA)
require(shiny)
require(shinyBS)

```

<<<<<<< HEAD
This R Markdown/Shiny document that allow the user to plot different Weakest Link models and predictors using METABRIC and Stimulated data.   
## Part A: Choosing/Plotting a dataset
=======

## Choosing a dataset to plot

Choose your dataset: either *METABRIC* or *Simulated data*.  If *Simulated data* is chosen, you can adjust the population size, as well as the a's and b's.   If *METABRIC* is chosen, choose a pair of PAM50 genes as the predictors.

>>>>>>> 6eb5cba0d8eeb96a54f5caca5db344b5ce64580a


```{r echo=FALSE}
rvalues = reactiveValues()
<<<<<<< HEAD
inputPanel(
  radioButtons("chosen_data", label = "Dataset:",
               choices = c("Metabric", "Simulated"), selected = "Simulated"),
  conditionalPanel("input.chosen_data == 'Simulated'",
                   numericInput("sim_population", 
                                label = "Simulated Population",
                                min = 0, max = 500, value = 100),
=======
radioButtons("chosen_data", label = "Dataset:",
               choices = c("Metabric", "Simulated"), 
               selected = "Simulated",inline = TRUE
  )

```

```{r conditionalDataplots}
output$conditionalDataplots = 
  renderUI(
    div(
      conditionalPanel(
        "input.chosen_data == 'Simulated'",
        fluidRow(
          column(2,
                 numericInput(width = 100,
                              "sim_population", 
                              label = "Simulated Sample Size",
                              min = 0, max = 500, value = 100),
                 actionButton('resample', 'resample')),
          column(3,
                 span(
>>>>>>> 6eb5cba0d8eeb96a54f5caca5db344b5ce64580a
                   sliderInput("a1_adjust", label = "A1 adjustment:",
                               min = 1, max = 10, value = 1, step = 1), 
                   sliderInput("a2_adjust", label = "A2 adjustment:",
                               min = 1, max = 10, value = 2, step = 1), 
                   sliderInput("b1_adjust", label = "B1 adjustment:",
                               min = 1, max = 10, value = 1, step = 1), 
                   sliderInput("b2_adjust", label = "B2 adjustment:",
                               min = 1, max = 10, value = 2, step = 1)
                 )
          ),
          column(7,
                 plotOutput('fittedSimulated', width = '350px') 
          )
        )
      ),
      conditionalPanel(
        "input.chosen_data == 'Metabric'",
        fluidRow(
          column(5,  
                 selectInput("Gene1", label = "Gene 1",
                             choices = p45, selected = 'UBE2C'),
                 selectInput("Gene2", label = "Gene 2",
                             choices = p45, selected = 'PTTG1'),
                 selectInput("Endpoints", label = "Endpoints",
                             choices = c("D7")
                 )
          ),
          column(7,
                 plotOutput('fittedMetabric', width = '350px') 
          )
        ) 
      )
    )
  )
```

```{r}
output$fittedMetabric = renderPlot({
  #if (input$chosen_data == 'Metabric'){
    g1= input$Gene1
    g2= input$Gene2
    print(g2)
    resultFitted = analyzeAPair(g1 = g1, g2 = g2,
                                endpoint = mb$D7,  # Surv(mb$time, mb$cens) 
                                delta = 'fit',
                                printBoxplot = FALSE,
                                plottheData= TRUE)
    drawCOU(x1 = mb[[g1]], x2 = mb[[g2]], delta = 0, FhatStyle = 'normal',
            col='blue')
    drawCOU(x1 = mb[[g1]], x2 = mb[[g2]], delta = 0, FhatStyle = 'ecdf',
            col='purple')
  }
<<<<<<< HEAD
  else{
    rvalues$sim_data = WLContinuousdata(n = input$sim_population, 
                                        a1 = input$a1_adjust, 
                                        a2 = input$a2_adjust,
                                        b1 = input$b1_adjust,
                                        b2 = input$b2_adjust)
    fitQWLprobit(rvalues$sim_data, delta = c(-3, 3))
    drawCOUline(a1 = input$a1_adjust, 
                a2 = input$a2_adjust,
                b1 = input$b1_adjust,
                b2 = input$b2_adjust, 
                col = "purple",
                lty = 2,
                lwd = 2)
    
    
  }
  
}
=======
>>>>>>> 6eb5cba0d8eeb96a54f5caca5db344b5ce64580a
)

output$fittedSimulated = renderPlot({
    input$resample  ### Resampling button 
    try({
    rvalues$sim_data = WLContinuousdata(n = input$sim_population, 
                                        a1 = input$a1_adjust, 
                                        a2 = input$a2_adjust,
                                        b1 = input$b1_adjust,
                                        b2 = input$b2_adjust)
    fitQWLprobit(rvalues$sim_data, delta = c(-3, 3))
    drawCOUline(a1 = input$a1_adjust, 
                a2 = input$a2_adjust,
                b1 = input$b1_adjust,
                b2 = input$b2_adjust, 
                col = "purple",
                lty = 2,
                lwd = 2)
    })
})
```

```{r}
uiOutput('conditionalDataplots')

```


## Estimation Methods
Click each checkbox to plot each estimation method.  More than one method can be plotted at a time, so comparisons between all four methods can be made with both datasets.
```{r tabsets, echo=FALSE}
inputPanel(
  checkboxGroupInput("estimethods", label = "Estimation Methods",
                     choices = c("Generated Stimulated Annealing", 
                                 "Quantitative Stitching (Delta Fixed)",
                                 "Quantitative Stitching (Delta Fitted)",
                                 "Conditional Optimization")), 
  numericInput("Delta", 
               label = "Delta",
               min = -4, max = 4, value = 0),
  
  uiOutput("estimationplots")
  
)

output$estimationplots = renderUI(expr = {
  if ("Generated Stimulated Annealing" %in% input$estimethods){
    starting_vector = c(a1=0, a2=0, b1=1, b2=1)
    sv = starting_vector
    if (input$chosen_data == "Metabric"){
      mydata = data.frame(x1 = mb[[input$Gene1]], 
                          x2 = mb[[input$Gene2]], 
                          y = mb[[input$Endpoints]])  
    }
    else{
      mydata = rvalues$sim_data
    }
    print(dim(mydata))
    print(names(mydata))
    myfn = function(a1a2b1b2){
      -1 * Likelydata(a1a2b1b2 = a1a2b1b2, data = mydata)
    }
    
    SA = GenSA(par = sv, fn = myfn, lower = sv - 3, upper = sv + 3, 
               control = list(maxit = 100))
    drawCOUline(a1 = SA$par["a1"], 
                a2 = SA$par["a2"], 
                b1 = SA$par['b1'], 
                b2 = SA$par["b2"])
    
  }
  
  if ("Quantitative Stitching (Delta Fixed)" %in% input$estimethods){
    if (input$chosen_data == "Metabric"){
      fitQWLprobit(theData = input$chosen_data, 
                   x1 = mb[[input$Gene1]], 
                   x2 = mb[[input$Gene2]], 
                   y = mb[[input$Endpoints]],   
                   delta = input$Delta)
    }
    
  }
  if ("Quantitative Stitching (Delta Fitted)" %in% input$estimethods){
<<<<<<< HEAD
    if (input$chosen_data == "Metabric"){
      fitQWLprobit(theData = input$chosen_data, 
                   x1 = mb[[input$Gene1]], 
                   x2 = mb[[input$Gene2]], 
                   y = mb[[input$Endpoints]])
    }
  }
    if ("ConditionalMaximum Optimization" %in% input$estimethods){
      estimateline = ConMaxStep()
      with(estimateline, 
           drawCOUline(a1maximizer,a2maximizer,b1maximizer,b2maximizer,
                       col = "purple", 
                       lty = 2, 
                       lwd = 2) 
      )
      
      
    }
    
  })
=======
    fitQWLprobit(theData = input$chosen_data, 
                 x1 = mb[[input$Gene1]], 
                 x2 = mb[[input$Gene2]], 
                 y = mb[[input$Endpoints]])
  }
  if ("ConditionalMaximum Optimization" %in% input$estimethods){
    estimateline = ConMaxStep()
    with(estimateline, 
         drawCOUline(a1maximizer,a2maximizer,b1maximizer,b2maximizer,
                     col = "purple", 
                     lty = 2, 
                     lwd = 2) 
    )
  }
})
>>>>>>> 6eb5cba0d8eeb96a54f5caca5db344b5ce64580a

```



